### PR TITLE
Update SRC membership

### PR DESCRIPTION
**Pull request by haydentherapper**
I am proposing that Cody Soyland from GitHub join the SRC. He has been contributing to the Sigstore infrastructure and is ramped up on the requirements of the SRC.

Additionally, having spoken to both offline, Dan and Asra will be leaving the SRC and moving to emeritus.

### CODE REVIEW

**Comment by haydentherapper** [comment]
cc other members of SRC for +1s: @bobcallaway @lukehinds and myself

+1 from me

cc @codysoyland

**Comment by haydentherapper** [comment]
cc @trevrosen also

**Review by bobcallaway — APPROVED** [review]

**Comment by haydentherapper** [comment]
Bumping for review

**Review by codysoyland — APPROVED** [review]
"...and my axe!"

**Review by lukehinds — APPROVED** [review]
+1

**Pull request merged**
